// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function CheckOutlookInstalled() {
  return window['go']['main']['App']['CheckOutlookInstalled']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportLogsToCSV(arg1) {
  return window['go']['main']['App']['ExportLogsToCSV'](arg1);
}

export function GetAllTemplates() {
  return window['go']['main']['App']['GetAllTemplates']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetMergeFields() {
  return window['go']['main']['App']['GetMergeFields']();
}

export function GetMergeFieldsFromHeaders(arg1) {
  return window['go']['main']['App']['GetMergeFieldsFromHeaders'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSendingDelay() {
  return window['go']['main']['App']['GetSendingDelay']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function ParseContactFile(arg1) {
  return window['go']['main']['App']['ParseContactFile'](arg1);
}

export function PreviewMerge(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PreviewMerge'](arg1, arg2, arg3, arg4, arg5);
}

export function PreviewMergeForContact(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewMergeForContact'](arg1, arg2, arg3);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SelectAttachments() {
  return window['go']['main']['App']['SelectAttachments']();
}

export function SelectContactFile() {
  return window['go']['main']['App']['SelectContactFile']();
}

export function SendBulkEmails(arg1) {
  return window['go']['main']['App']['SendBulkEmails'](arg1);
}

export function SendTestEmail(arg1) {
  return window['go']['main']['App']['SendTestEmail'](arg1);
}

export function SetSendingDelay(arg1) {
  return window['go']['main']['App']['SetSendingDelay'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateTemplate(arg1) {
  return window['go']['main']['App']['ValidateTemplate'](arg1);
}
