// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {storage} from '../models';
import {campaign} from '../models';
import {services} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function CancelCampaign():Promise<void>;

export function CheckOutlookInstalled():Promise<void>;

export function ClearCampaignHistory():Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function DeleteCampaign(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExportLogsToCSV(arg1:Array<models.EmailLog>):Promise<string>;

export function GetAllTemplates():Promise<Array<models.EmailTemplate>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetCampaign(arg1:string):Promise<storage.CampaignRecord>;

export function GetCampaignHistory():Promise<Array<storage.CampaignRecord>>;

export function GetFileInfo(arg1:string):Promise<models.FileInfo>;

export function GetMergeFields():Promise<Array<string>>;

export function GetMergeFieldsFromHeaders(arg1:Array<string>):Promise<Array<string>>;

export function GetOutlookStatus():Promise<campaign.SenderStatus>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSenderCapabilities():Promise<campaign.SenderCapabilities>;

export function GetSendingDelay():Promise<number>;

export function GetSettings():Promise<models.AppSettings>;

export function GetTemplate(arg1:string):Promise<models.EmailTemplate>;

export function ParseContactFile(arg1:string):Promise<models.ParseResult>;

export function PreflightCampaign(arg1:models.EmailRequest):Promise<campaign.PreflightResult>;

export function PreviewMerge(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<services.MergeResult>;

export function PreviewMergeForContact(arg1:string,arg2:string,arg3:models.Contact):Promise<services.MergeResult>;

export function RetryCampaign(arg1:string):Promise<campaign.CampaignResult>;

export function RetryFailed(arg1:models.EmailRequest):Promise<campaign.CampaignResult>;

export function SaveTemplate(arg1:models.EmailTemplate):Promise<models.EmailTemplate>;

export function SelectAttachments():Promise<Array<string>>;

export function SelectContactFile():Promise<string>;

export function SendBulkEmails(arg1:models.EmailRequest):Promise<campaign.CampaignResult>;

export function SendTestEmail(arg1:models.TestEmailRequest):Promise<void>;

export function SetSendingDelay(arg1:number):Promise<void>;

export function SetVersionInfo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:models.AppSettings):Promise<void>;

export function ValidateTemplate(arg1:string):Promise<Array<string>>;
